name: Code-Analysis

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 5:00 AM UTC (7:00 AM CEST)

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        uv sync --all-extras
    - name: Run the pre-commit hook
      run: |
        uv run pre-commit run --all-files
